// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxMra_f80ZhFUb8y8_8EI-DMjDhDSlDLM',
    appId: '1:972073683107:web:d124dbfcd6f6284f7a5716',
    messagingSenderId: '972073683107',
    projectId: 'flutter-projects-4d1b6',
    authDomain: 'flutter-projects-4d1b6.firebaseapp.com',
    storageBucket: 'flutter-projects-4d1b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCglDuE0cR5Lds3K48ypsu8PEqTNOSJu8E',
    appId: '1:972073683107:android:96a1a6c44bd8beb27a5716',
    messagingSenderId: '972073683107',
    projectId: 'flutter-projects-4d1b6',
    storageBucket: 'flutter-projects-4d1b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7-Q6NNPaX7rKYVBWsYQRbc_9dEwdh0fs',
    appId: '1:972073683107:ios:de6779169b51677c7a5716',
    messagingSenderId: '972073683107',
    projectId: 'flutter-projects-4d1b6',
    storageBucket: 'flutter-projects-4d1b6.firebasestorage.app',
    iosBundleId: 'com.nachoargu.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7-Q6NNPaX7rKYVBWsYQRbc_9dEwdh0fs',
    appId: '1:972073683107:ios:2d29b0113c3eb4b07a5716',
    messagingSenderId: '972073683107',
    projectId: 'flutter-projects-4d1b6',
    storageBucket: 'flutter-projects-4d1b6.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxMra_f80ZhFUb8y8_8EI-DMjDhDSlDLM',
    appId: '1:972073683107:web:3ff474287aeceac07a5716',
    messagingSenderId: '972073683107',
    projectId: 'flutter-projects-4d1b6',
    authDomain: 'flutter-projects-4d1b6.firebaseapp.com',
    storageBucket: 'flutter-projects-4d1b6.firebasestorage.app',
  );
}